### ISSUE TITLE
Enable DEP.

### ISSUE THREAD

**Issue by c-edw** [cryps1s/DARKSURGEON#25]
**Describe the solution you'd like**
Windows includes a security feature named Data Execution Prevention (DEP). This prevents potentially malicious code from being executed in data pages. This is to harden the operating system.

**Describe alternatives you've considered**
Most modern systems have this as a hardware feature I believe (EDB?).

**Additional context**
See [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366553(v=vs.85).aspx) for more info.

**Comment by cryps1s** [comment]
Merged in https://github.com/cryps1s/DARKSURGEON/pull/27.
